# <a name="exceptions"></a><span data-ttu-id="f2be9-101">Исключения</span><span class="sxs-lookup"><span data-stu-id="f2be9-101">Exceptions</span></span>

<span data-ttu-id="f2be9-102">Исключения в C# предоставляют структурированный, однородный и строго типобезопасный способ обработки системного уровня и уровня приложения условия ошибок.</span><span class="sxs-lookup"><span data-stu-id="f2be9-102">Exceptions in C# provide a structured, uniform, and type-safe way of handling both system level and application level error conditions.</span></span> <span data-ttu-id="f2be9-103">Механизм обработки исключений в C# очень похож на, c++, с помощью несколько важных различий:</span><span class="sxs-lookup"><span data-stu-id="f2be9-103">The exception mechanism in C# is quite similar to that of C++, with a few important differences:</span></span>

*  <span data-ttu-id="f2be9-104">В C# все исключения должны быть представлены с помощью экземпляра типа класса, производного от `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="f2be9-104">In C#, all exceptions must be represented by an instance of a class type derived from `System.Exception`.</span></span> <span data-ttu-id="f2be9-105">В C++ можно использовать любое значение любого типа, который представляет исключение.</span><span class="sxs-lookup"><span data-stu-id="f2be9-105">In C++, any value of any type can be used to represent an exception.</span></span>
*  <span data-ttu-id="f2be9-106">В C# блок finally ([оператора try](statements.md#the-try-statement)) может использоваться для записи кода завершения, который выполняется в нормальном выполнении и исключительных условий.</span><span class="sxs-lookup"><span data-stu-id="f2be9-106">In C#, a finally block ([The try statement](statements.md#the-try-statement)) can be used to write termination code that executes in both normal execution and exceptional conditions.</span></span> <span data-ttu-id="f2be9-107">Такой код будет сложно создавать на языке C++ без дублирования кода.</span><span class="sxs-lookup"><span data-stu-id="f2be9-107">Such code is difficult to write in C++ without duplicating code.</span></span>
*  <span data-ttu-id="f2be9-108">В C# исключения системного уровня, например переполнение, деление на ноль и null разыменовывает четко определенные классы исключений и находятся на одном уровне с состояниями ошибки уровня приложения.</span><span class="sxs-lookup"><span data-stu-id="f2be9-108">In C#, system-level exceptions such as overflow, divide-by-zero, and null dereferences have well defined exception classes and are on a par with application-level error conditions.</span></span>

## <a name="causes-of-exceptions"></a><span data-ttu-id="f2be9-109">Причины исключений</span><span class="sxs-lookup"><span data-stu-id="f2be9-109">Causes of exceptions</span></span>

<span data-ttu-id="f2be9-110">Исключение может вызываться двумя разными способами.</span><span class="sxs-lookup"><span data-stu-id="f2be9-110">Exception can be thrown in two different ways.</span></span>

*  <span data-ttu-id="f2be9-111">Объект `throw` инструкции ([инструкция throw](statements.md#the-throw-statement)) вызывает исключение немедленно и безусловно.</span><span class="sxs-lookup"><span data-stu-id="f2be9-111">A `throw` statement ([The throw statement](statements.md#the-throw-statement)) throws an exception immediately and unconditionally.</span></span> <span data-ttu-id="f2be9-112">Элемент управления никогда не достигает оператора, следующего `throw`.</span><span class="sxs-lookup"><span data-stu-id="f2be9-112">Control never reaches the statement immediately following the `throw`.</span></span>
*  <span data-ttu-id="f2be9-113">Определенные исключительных условий, возникающих во время обработки операторов C# и выражения вызывает исключение в определенных обстоятельствах, когда обычно не удается выполнить операцию.</span><span class="sxs-lookup"><span data-stu-id="f2be9-113">Certain exceptional conditions that arise during the processing of C# statements and expression cause an exception in certain circumstances when the operation cannot be completed normally.</span></span> <span data-ttu-id="f2be9-114">Например, операции деления целое число ([оператор деления](expressions.md#division-operator)) создает `System.DivideByZeroException` Если знаменатель равен нулю.</span><span class="sxs-lookup"><span data-stu-id="f2be9-114">For example, an integer division operation ([Division operator](expressions.md#division-operator)) throws a `System.DivideByZeroException` if the denominator is zero.</span></span> <span data-ttu-id="f2be9-115">См. в разделе [общие классы исключений](exceptions.md#common-exception-classes) список различных исключений, которые могут возникнуть таким образом.</span><span class="sxs-lookup"><span data-stu-id="f2be9-115">See [Common Exception Classes](exceptions.md#common-exception-classes) for a list of the various exceptions that can occur in this way.</span></span>

## <a name="the-systemexception-class"></a><span data-ttu-id="f2be9-116">Класс System.Exception</span><span class="sxs-lookup"><span data-stu-id="f2be9-116">The System.Exception class</span></span>

<span data-ttu-id="f2be9-117">`System.Exception` Класс является базовым типом для всех исключений.</span><span class="sxs-lookup"><span data-stu-id="f2be9-117">The `System.Exception` class is the base type of all exceptions.</span></span> <span data-ttu-id="f2be9-118">Этот класс имеет несколько важных свойств, которые совместно используют все исключения.</span><span class="sxs-lookup"><span data-stu-id="f2be9-118">This class has a few notable properties that all exceptions share:</span></span>

*  <span data-ttu-id="f2be9-119">`Message` является свойством только для чтения типа `string` , содержащий понятное описание причины исключения.</span><span class="sxs-lookup"><span data-stu-id="f2be9-119">`Message` is a read-only property of type `string` that contains a human-readable description of the reason for the exception.</span></span>
*  <span data-ttu-id="f2be9-120">`InnerException` является свойством только для чтения типа `Exception`.</span><span class="sxs-lookup"><span data-stu-id="f2be9-120">`InnerException` is a read-only property of type `Exception`.</span></span> <span data-ttu-id="f2be9-121">Если его значение не равно null, он ссылается на исключение, вызвавшее текущее исключение — то есть, текущее исключение возникло в блоке catch обработки `InnerException`.</span><span class="sxs-lookup"><span data-stu-id="f2be9-121">If its value is non-null, it refers to the exception that caused the current exception—that is, the current exception was raised in a catch block handling the `InnerException`.</span></span> <span data-ttu-id="f2be9-122">В противном случае его значение null, указывает, что это исключение не было вызвано другое исключение.</span><span class="sxs-lookup"><span data-stu-id="f2be9-122">Otherwise, its value is null, indicating that this exception was not caused by another exception.</span></span> <span data-ttu-id="f2be9-123">Количество объектов исключений, которые соединены друг с другом, таким образом может быть произвольным.</span><span class="sxs-lookup"><span data-stu-id="f2be9-123">The number of exception objects chained together in this manner can be arbitrary.</span></span>

<span data-ttu-id="f2be9-124">Значения этих свойств можно указать в вызовах конструктору экземпляра для `System.Exception`.</span><span class="sxs-lookup"><span data-stu-id="f2be9-124">The value of these properties can be specified in calls to the instance constructor for `System.Exception`.</span></span>

## <a name="how-exceptions-are-handled"></a><span data-ttu-id="f2be9-125">Обработка исключений</span><span class="sxs-lookup"><span data-stu-id="f2be9-125">How exceptions are handled</span></span>

<span data-ttu-id="f2be9-126">Исключения обрабатываются `try` инструкции ([оператора try](statements.md#the-try-statement)).</span><span class="sxs-lookup"><span data-stu-id="f2be9-126">Exceptions are handled by a `try` statement ([The try statement](statements.md#the-try-statement)).</span></span>

<span data-ttu-id="f2be9-127">При возникновении исключения, система выполняет поиск ближайших `catch` предложение, которое может обработать исключение, как определяется типом времени выполнения исключения.</span><span class="sxs-lookup"><span data-stu-id="f2be9-127">When an exception occurs, the system searches for the nearest `catch` clause that can handle the exception, as determined by the run-time type of the exception.</span></span> <span data-ttu-id="f2be9-128">Во-первых, текущий метод ищется лексически заключения `try` инструкции и предложения соответствующего блока catch оператора try считаются в порядке.</span><span class="sxs-lookup"><span data-stu-id="f2be9-128">First, the current method is searched for a lexically enclosing `try` statement, and the associated catch clauses of the try statement are considered in order.</span></span> <span data-ttu-id="f2be9-129">В случае неудачи, метод, который вызвал текущий метод ищется лексически заключения `try` инструкцию, которая содержит точку вызова текущего метода.</span><span class="sxs-lookup"><span data-stu-id="f2be9-129">If that fails, the method that called the current method is searched for a lexically enclosing `try` statement that encloses the point of the call to the current method.</span></span> <span data-ttu-id="f2be9-130">Этот поиск продолжается, пока `catch` предложение найдено, который может обрабатывать текущее исключение, назвав имеет того же класса или базового класса, типа времени выполнения исключения класса исключения.</span><span class="sxs-lookup"><span data-stu-id="f2be9-130">This search continues until a `catch` clause is found that can handle the current exception, by naming an exception class that is of the same class, or a base class, of the run-time type of the exception being thrown.</span></span> <span data-ttu-id="f2be9-131">Объект `catch` предложение, которое не назовите класс исключения может обрабатывать любое исключение.</span><span class="sxs-lookup"><span data-stu-id="f2be9-131">A `catch` clause that doesn't name an exception class can handle any exception.</span></span>

<span data-ttu-id="f2be9-132">После обнаружения подходящего оператора catch система готовится к передаче управления в первый оператор в предложении catch.</span><span class="sxs-lookup"><span data-stu-id="f2be9-132">Once a matching catch clause is found, the system prepares to transfer control to the first statement of the catch clause.</span></span> <span data-ttu-id="f2be9-133">Перед началом выполнения предложения catch, система сначала выполняет, в порядке, любой `finally` предложения, которые были связаны с инструкции try дополнительные вложенные, чем тот, который вызвал исключение.</span><span class="sxs-lookup"><span data-stu-id="f2be9-133">Before execution of the catch clause begins, the system first executes, in order, any `finally` clauses that were associated with try statements more nested that than the one that caught the exception.</span></span>

<span data-ttu-id="f2be9-134">Если нет подходящего оператора catch найден, возникает одно из следующих действий:</span><span class="sxs-lookup"><span data-stu-id="f2be9-134">If no matching catch clause is found, one of two things occurs:</span></span>

*  <span data-ttu-id="f2be9-135">Если поиск подходящего оператора catch достигает статический конструктор ([статические конструкторы](classes.md#static-constructors)) или инициализатор статического поля, а затем `System.TypeInitializationException` возникает в точке, запустившей вызов статического конструктора.</span><span class="sxs-lookup"><span data-stu-id="f2be9-135">If the search for a matching catch clause reaches a static constructor ([Static constructors](classes.md#static-constructors)) or static field initializer, then a `System.TypeInitializationException` is thrown at the point that triggered the invocation of the static constructor.</span></span> <span data-ttu-id="f2be9-136">Внутреннее исключение `System.TypeInitializationException` содержит исключение, которое изначально было выдано.</span><span class="sxs-lookup"><span data-stu-id="f2be9-136">The inner exception of the `System.TypeInitializationException` contains the exception that was originally thrown.</span></span>
*  <span data-ttu-id="f2be9-137">Если для сопоставления предложения catch достигается код, который изначально запуска потока, завершается выполнение потока.</span><span class="sxs-lookup"><span data-stu-id="f2be9-137">If the search for matching catch clauses reaches the code that initially started the thread, then execution of the thread is terminated.</span></span> <span data-ttu-id="f2be9-138">Влияние прекращение их действия определяется реализацией.</span><span class="sxs-lookup"><span data-stu-id="f2be9-138">The impact of such termination is implementation-defined.</span></span>

<span data-ttu-id="f2be9-139">Исключения, возникающие при выполнении деструктора заслуживают отдельного упоминания.</span><span class="sxs-lookup"><span data-stu-id="f2be9-139">Exceptions that occur during destructor execution are worth special mention.</span></span> <span data-ttu-id="f2be9-140">Если исключение возникает при выполнении деструктора, и это исключение не перехватывается, выполнение этого деструктора завершается, и вызывается деструктор базового класса (если таковые имеются).</span><span class="sxs-lookup"><span data-stu-id="f2be9-140">If an exception occurs during destructor execution, and that exception is not caught, then the execution of that destructor is terminated and the destructor of the base class (if any) is called.</span></span> <span data-ttu-id="f2be9-141">Если нет базового класса (как в случае `object` типа) или если деструктор базового класса, то исключение было удалено.</span><span class="sxs-lookup"><span data-stu-id="f2be9-141">If there is no base class (as in the case of the `object` type) or if there is no base class destructor, then the exception is discarded.</span></span>

## <a name="common-exception-classes"></a><span data-ttu-id="f2be9-142">Общие классы исключений</span><span class="sxs-lookup"><span data-stu-id="f2be9-142">Common Exception Classes</span></span>

<span data-ttu-id="f2be9-143">Следующие исключения создаются с помощью определенных операций на C#.</span><span class="sxs-lookup"><span data-stu-id="f2be9-143">The following exceptions are thrown by certain C# operations.</span></span>

|                                      |                |
|--------------------------------------|----------------|
| `System.ArithmeticException`         | <span data-ttu-id="f2be9-144">Базовый класс для исключений, которые возникают при выполнении арифметических операций, таких как `System.DivideByZeroException` и `System.OverflowException`.</span><span class="sxs-lookup"><span data-stu-id="f2be9-144">A base class for exceptions that occur during arithmetic operations, such as `System.DivideByZeroException` and `System.OverflowException`.</span></span> | 
| `System.ArrayTypeMismatchException`  | <span data-ttu-id="f2be9-145">Создается в случае сбоя хранилища в массив, так как фактический тип хранимых элемента несовместим с фактическим типом массива.</span><span class="sxs-lookup"><span data-stu-id="f2be9-145">Thrown when a store into an array fails because the actual type of the stored element is incompatible with the actual type of the array.</span></span> | 
| `System.DivideByZeroException`       | <span data-ttu-id="f2be9-146">Возникает, когда происходит при попытке деления целого значения на ноль.</span><span class="sxs-lookup"><span data-stu-id="f2be9-146">Thrown when an attempt to divide an integral value by zero occurs.</span></span> | 
| `System.IndexOutOfRangeException`    | <span data-ttu-id="f2be9-147">Возникает при попытке индексирования массива с помощью индекса, которое меньше нуля или выходит за границы массива.</span><span class="sxs-lookup"><span data-stu-id="f2be9-147">Thrown when an attempt to index an array via an index that is less than zero or outside the bounds of the array.</span></span> | 
| `System.InvalidCastException`        | <span data-ttu-id="f2be9-148">Возникает, если явное преобразование из базового типа или интерфейса в производный тип завершается ошибкой во время выполнения.</span><span class="sxs-lookup"><span data-stu-id="f2be9-148">Thrown when an explicit conversion from a base type or interface to a derived type fails at run time.</span></span> | 
| `System.NullReferenceException`      | <span data-ttu-id="f2be9-149">Возникает, когда `null` ссылка используется способом, который вызывает упоминаемого объекта обязательным.</span><span class="sxs-lookup"><span data-stu-id="f2be9-149">Thrown when a `null` reference is used in a way that causes the referenced object to be required.</span></span> | 
| `System.OutOfMemoryException`        | <span data-ttu-id="f2be9-150">Возникает при попытке выделения памяти (через `new`) завершается сбоем.</span><span class="sxs-lookup"><span data-stu-id="f2be9-150">Thrown when an attempt to allocate memory (via `new`) fails.</span></span> | 
| `System.OverflowException`           | <span data-ttu-id="f2be9-151">Возникает при переполнении арифметической операции в контексте `checked`.</span><span class="sxs-lookup"><span data-stu-id="f2be9-151">Thrown when an arithmetic operation in a `checked` context overflows.</span></span> | 
| `System.StackOverflowException`      | <span data-ttu-id="f2be9-152">Возникает, когда стек выполнения переполнен слишком много вызовов метода, ожидающих утверждения; Обычно это указывает на очень глубокой или неограниченной рекурсии.</span><span class="sxs-lookup"><span data-stu-id="f2be9-152">Thrown when the execution stack is exhausted by having too many pending method calls; typically indicative of very deep or unbounded recursion.</span></span> | 
| `System.TypeInitializationException` | <span data-ttu-id="f2be9-153">Возникает, когда статический конструктор создает исключение и нет `catch` предложений существует перехватить.</span><span class="sxs-lookup"><span data-stu-id="f2be9-153">Thrown when a static constructor throws an exception, and no `catch` clauses exists to catch it.</span></span> | 
